### ISSUE TITLE
Latest version breaks now.sh 

### ISSUE THREAD

**Issue by yatagasaru** [amio/micro-fork#82]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/37947184/71476658-b50bd880-2818-11ea-96bd-e5dd01aed363.png">

Log from zeit now : 
```START RequestId: 4cddf933-24c0-46d5-afea-e237a31be01d Version: $LATEST
2019-12-26T12:35:02.418Z	4cddf933-24c0-46d5-afea-e237a31be01d	Unhandled rejection: ReferenceError: URL is not defined
    at Object.handler (/var/task/node_modules/micro-fork/index.js:15:39)
    at Router.lookup (/var/task/node_modules/find-my-way/index.js:349:14)
    at /var/task/node_modules/micro-fork/index.js:8:33
    at Server.http_1.Server (/var/task/___now_helpers.js:875:19)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
END RequestId: 4cddf933-24c0-46d5-afea-e237a31be01d
REPORT RequestId: 4cddf933-24c0-46d5-afea-e237a31be01d	Duration: 49.29 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 38 MB	
RequestId: 4cddf933-24c0-46d5-afea-e237a31be01d Process exited before completing request


START RequestId: 7421c456-6c26-4c9e-a582-69586a9066de Version: $LATEST
END RequestId: 7421c456-6c26-4c9e-a582-69586a9066de
REPORT RequestId: 7421c456-6c26-4c9e-a582-69586a9066de	Duration: 18.29 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 38 MB	

START RequestId: 0eeff186-c291-40b8-b75a-c894f0a863ee Version: $LATEST
2019-12-26T12:35:11.180Z	0eeff186-c291-40b8-b75a-c894f0a863ee	Unhandled rejection: ReferenceError: URL is not defined
    at Object.handler (/var/task/node_modules/micro-fork/index.js:15:39)
    at Router.lookup (/var/task/node_modules/find-my-way/index.js:349:14)
    at /var/task/node_modules/micro-fork/index.js:8:33
    at Server.http_1.Server (/var/task/___now_helpers.js:875:19)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
END RequestId: 0eeff186-c291-40b8-b75a-c894f0a863ee
REPORT RequestId: 0eeff186-c291-40b8-b75a-c894f0a863ee	Duration: 55.10 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 38 MB	
RequestId: 0eeff186-c291-40b8-b75a-c894f0a863ee Process exited before completing request


START RequestId: cbfd15d9-eff2-43f2-8a97-03beb94601be Version: $LATEST
2019-12-26T12:35:10.454Z	cbfd15d9-eff2-43f2-8a97-03beb94601be	Unhandled rejection: ReferenceError: URL is not defined
    at Object.handler (/var/task/node_modules/micro-fork/index.js:15:39)
    at Router.lookup (/var/task/node_modules/find-my-way/index.js:349:14)
    at /var/task/node_modules/micro-fork/index.js:8:33
    at Server.http_1.Server (/var/task/___now_helpers.js:875:19)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
END RequestId: cbfd15d9-eff2-43f2-8a97-03beb94601be
REPORT RequestId: cbfd15d9-eff2-43f2-8a97-03beb94601be	Duration: 38.75 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 38 MB	
RequestId: cbfd15d9-eff2-43f2-8a97-03beb94601be Process exited before completing request


START RequestId: 07a043ff-2724-4510-8309-25fd9fd48505 Version: $LATEST
2019-12-26T12:47:35.051Z	07a043ff-2724-4510-8309-25fd9fd48505	Unhandled rejection: ReferenceError: URL is not defined
    at Object.handler (/var/task/node_modules/micro-fork/index.js:15:39)
    at Router.lookup (/var/task/node_modules/find-my-way/index.js:349:14)
    at /var/task/node_modules/micro-fork/index.js:8:33
    at Server.http_1.Server (/var/task/___now_helpers.js:875:19)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
END RequestId: 07a043ff-2724-4510-8309-25fd9fd48505
REPORT RequestId: 07a043ff-2724-4510-8309-25fd9fd48505	Duration: 40.92 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 38 MB	
RequestId: 07a043ff-2724-4510-8309-25fd9fd48505 Process exited before completing request
```

**Comment by amio** [comment]
V3 dropped support for Node.js v8 https://github.com/amio/micro-fork/releases/tag/v3.0.0

@yatagasaru you may update your project config to use later nodejs version, or downgrade micro-fork to v2, it's identical in features

**Comment by amio** [comment]
Please reopen if you have any further questions.

**Comment by yatagasaru** [comment]
> V3 dropped support for Node.js v8 https://github.com/amio/micro-fork/releases/tag/v3.0.0
> 
> @yatagasaru you may update your project config to use later nodejs version, or downgrade micro-fork to v2, it's identical in features

thank you
